### ISSUE TITLE
Do not ask for equals/hashCode on the sequential specification until necessary

### ISSUE THREAD

**Issue by ndkoval** [Kotlin/kotlinx-lincheck#135]
Usually, the verification phase is super-fast, even with default `equals` and `hashCode` implementations. However, it might be critical to provide custom implementations when testing scenarios are large or when the data structure operations are expensive.

Let's not require `equals`/`hashCode` to be implemented if the verification phase takes excepted time -- Lincheck should neither throw an exception nor print a warning. However, when the verification process takes an unexpectedly long time, it would be helpful to print a warning with instructions on how to implement `equals` and `hashCode`.

**Comment by ndkoval** [comment]
These messages are really annoying...
```
To make verification faster, you can specify the state equivalence relation on your sequential specification.
At the current moment, `MultiMapTest` does not specify it, or the equivalence relation implementation is incorrect.
To fix this, please implement `equals()` and `hashCode()` functions on `MultiMapTest`; the simplest way is to extend `VerifierState`
and override the `extractState()` function, which is called at once and the result of which is used for further `equals()` and `hashCode()` invocations.
```

**Comment by ndkoval** [comment]
We need to make experiments to decide when `equals/hashCode` implementations start helping. After that, we can have heuristics that enables asking for `equals/hashCode` only when it seems necessary.

**Comment by ndkoval** [comment]
Let's also remove the `requireStateEquivalenceImplCheck` parameter: I cannot find a single usage.

**Comment by avpotapov00** [comment]
As experiments shown, there is no explicit correlation between equals/hashcode presence and verification time and a whole test time. Equals and hashcode can significantly improve or mess up performance only if a scenario is really big. In real tasks it can be if threads count is >= 4. 
We measured perfomace with and without equals/hashcode on tests: 

This plot describes 
- BufferedChannel
- ConcurrentHashMap
- ConcurrentLinkedDeque
- Counter
- ConcurrentSkipListMap
- LockFreeTaskQueue (QuiescentConsistency)
- ConcurrentHashMap

The graph below describes whether equals / hashcode improves or worsens verification time. The x-axis value is equal to the difference between the verification time without equals / hashcode and with equals / hashcode in milliseconds for the same experiment. The y-axis is the number of threads.
![verification_time_delta__threads](https://user-images.githubusercontent.com/45040429/230376348-8c3aaa73-2f58-4889-97dd-5825b0ea7d92.png)

On most tests, there is not much difference, but on those where the difference is significant, the presence of equals / hashcode often worsens the results.
The lack of correlation is explained as follows: although the ability to reuse states in an LTS graph reduces the graph, making its traversal faster, sometimes the comparison methods, if they are present, are not fast enough, so verification takes longer.

According to the current results of the experiments, it was decided to mark VeriferState as @Deprecated and completely remove the warning about the absence of equals / hashcode, since this option can not only improve, but also worsen the running time and also complicates the use of the framework.

**Comment by ndkoval** [comment]
These results are really surprising, thanks @avpotapov00 for the analysis!

**Comment by avpotapov00** [comment]
Experiments shown the following results:
![histogram](https://user-images.githubusercontent.com/45040429/230442879-4f8a259c-c0f7-4e10-a5f3-22080ed50616.png)

**Comment by ndkoval** [comment]
It would be better to show the percentage of the time spent in the verification phase.

**Comment by avpotapov00** [comment]
Here it is. 
![percent](https://user-images.githubusercontent.com/45040429/230587032-6032f009-e159-4791-bb76-b7846755569d.png)

**Comment by avpotapov00** [comment]
So I propose to keep current `HashMap` states holder implementation in LTS structure, to deprecate VerifierState and remove the `requireStateEquivalenceImplCheck` parameter. Annoying warnings about equals/hashcode will be removed as well.

**Comment by ndkoval** [comment]
fixed

**Comment by panchenko** [comment]
I would like to understand how to replace deprecated `VerifierState` in existing tests after updating the Lincheck dependency.
Unfortunately, there is some lack of documentation.
Could you please advice?

The question is about [this test](https://github.com/grpc/grpc-java/blob/87b27b154538eaa3114c7280f02da2c4fdb0c91f/servlet/src/threadingTest/java/io/grpc/servlet/AsyncServletOutputStreamWriterConcurrencyTest.java) which implements the method in the following way:
```java
  @Override
  protected Object extractState() {
    return bytesWritten; // returns int field
  }
```

What would be the equivalent code without `VerifierState` ? 
implement equals & hashCode?
annotate that field somehow?
something else?

**Comment by eupp** [comment]
Hi @panchenko !

> implement equals & hashCode?

Yes, this is the intended workflow in the current version of Lincheck. 
Lincheck uses the datastructure's `equals` and `hashCode` internally to compare the instances of objects. 
To be more precise, it uses the equals/hashcode of the class you pass to `LinChecker.check` function, which is `AsyncServletOutputStreamWriterConcurrencyTest` in your test.

**Comment by ndkoval** [comment]
@panchenko however, you can safely drop them -- most likely it won't affect performance.
