### ISSUE TITLE
[PROPOSAL] Customizable scenario generator

### ISSUE THREAD

**Issue by sh-ad** [Kotlin/kotlinx-lincheck#90]
A сustomizable scenario generator must be able to create scenario according to the rules set by the user. The user should be able to influence the generation of both threads and specific operations.

Namely:
- order of operations
- operands of operations
- number of operations

Usage examples:
- binding a method to a separate thread
- import the script
- the ability to set arbitrary operations
- execution complementary operations in different threads with a common operand

**Comment by ndkoval** [comment]
Hi @sh-ad,

We have a prototype of a special DSL for specifying custom scenarios, please see #8. Does it solve the problem? If not, what would you add, and how?

**Comment by alefedor** [comment]
Hi @ndkoval,

This can be a generalization of both custom scenarios and operation groups.
For example, you may want to test a single-consumer single-producer concurrent queue with an iterator in a separate thread.
```
options.scenario {
  parallel {
    thread {
      actors(QueueTest::push)
      actorsInThread(4)
    }
    thread {
      actors(QueueTest::pop)
      actorsInThread(4)
    }
    thread {
      actors(QueueTest::iterate, QueueTest::size)
    }
  }
}
```

**Comment by ndkoval** [comment]
@alefedor do we have a real case for this feature? It is not a problem to _add_ the feature, but this will increase the code complexity, and we will need to support it. 

@sh-ad could you please explain your case in more detail?

**Comment by ndkoval** [comment]
As we do not see real-world use-cases at the moment, I am closing this proposal.

**Comment by xuanswe** [comment]
> As we do not see real-world use-cases at the moment, I am closing this proposal.

@ndkoval As I am new to LinCheck, I am not sure if this case will require customizing the scenario generator.
But I put it here anyway. Could you please check if we can solve this without customizing the scenario generator?

```
class AdderCounter {
  private val adder = LongAdder()

  fun increment() {
    adder.increment()
  }

  fun add(amount: Int) {
    adder.add(amount.toLong())
  }

  fun sum() = adder.sum()
}
```

We know that `LongAdder` is not linearizability because of `adder.sum()`.
I would like to test the scenario below:
* Before actors: `increment`, `add`
* Parallel actors: `increment`, `add`
* After actors: `sum`

How could we tell `ModelCheckingOptions` and `StressOptions` to generate scenarios with the restrictions above?

**Comment by xuanswe** [comment]
How about this case:

```
class BoundedQueue(private val capacity: Int) {
  private val queue = ArrayDeque<Int>()
  private var size = 0
  private val lock = ReentrantLock()
  private val hasSpaceCond = lock.newCondition()
  private val nonEmptyCond = lock.newCondition()

  fun enqueue(value: Int) {
    lock.withLock {
      while (size == capacity) {
        hasSpaceCond.await()
      }
      queue += value
      size++
      nonEmptyCond.signal()
    }
  }

  fun dequeue(): Int {
    lock.withLock {
      while (size == 0) {
        nonEmptyCond.await()
      }
      val value = queue.removeFirst()
      size--
      hasSpaceCond.signal()
      return value
    }
  }
}
```

This is a blocking data structure with `ReentrantLock`.

Let's test with `BoundedQueue(10)`. If LinCheck generates a scenario with 20 dequeue operations and 10 enqueue operations, the test will be blocked because 10 dequeue operations cannot acquire the lock.

To ensure not blocking the test and it can finish, we need to have restriction for the number of enqueue operations and dequeue operations. How could we do it with LinCheck?

**Comment by xuanswe** [comment]
> As we do not see real-world use-cases at the moment, I am closing this proposal.

@ndkoval Do you think my examples above are good enough to reopen this ticket or do you need more examples?

**Comment by xuanswe** [comment]
What do you think if we allow to have an option to "disable the provided generator" and run only custom scenarios?
I think with just this option, many cases could be solved already without the need of a customized scenario generator API.
